### ISSUE TITLE
RFC mission statement

### ISSUE THREAD

**Issue by piogor** [tango-controls/rfc#67]
Following discussion on the meeting, this issue is to gather ideas for formulation of a clear goal of the specification. The mission statement should be a reference for:
- being sure what should and what shouldn't be included in the RFCs
- reviewing/accepting proposals
- measuring the success

**Comment by piogor** [comment]
_The first proposition, to start:_

At this stage, the goal of the RFC project is to have a formal specification of the current Tango Controls, which is terminology and  protocol behaviour.
It will be useful for verification if the existing implementation and maintenance work is what is expected by the Community. 

Later, it will be a base for Tango v10 specification.

**Comment by david-erb** [comment]
Not being sure how the RFC would help with current verification and maintenance, I will address the v10.  I think the RFC for v9 would be a useful starting place for the v10 RFC.  That is, when the time comes to write v10, we make a copy the v9 RFC and start discussing what to keep, what to remove and what to add.  What this means to us now as we write the v9 RFC, is we want it to have good coverage of everything v9.  Not only protocols, but also other things in common use such as utilities, apis and conventions.  In a word, the v9 RFC should cover v9 as a system, and not just how programs talk to each other.  Concepts are more important to summarize than details.  Too much detail will be wasted on v10, since the v10 designers will discard things which are too low-level  and restrictive.

**Comment by piogor** [comment]
Done with #85
