### ISSUE TITLE
Setup link convention

### ISSUE THREAD

**Issue by piogor** [tango-controls/rfc#88]
It would be good if all RFCs use the same way of cross-referencing.

**Comment by bourtemb** [comment]
If we take the example of [RFC-4](https://github.com/tango-controls/rfc/blob/draft/4/Attribute.md) (Attribute), the links to other RFCs are currently like that:
`[RFC 2/Device](/2)`
which makes the reader go to the following github web page: https://github.com/tango-controls/rfc/tree/draft/2, which is not very friendly.

I think it would be more reader-friendly to link to the .md file directly since it is no longer named README.md, so in the case of RFC-2:
`[RFC 2/Device](/2/Device.md)`
In this case the reader would end up directly on this github web page: https://github.com/tango-controls/rfc/blob/draft/2/Device.md
